### ISSUE TITLE
Fix this in documentation

### ISSUE THREAD

**Issue by veremey** [Binaryify/vue-custom-scrollbar#16]
hi, @Binaryify .
Fix this settings in documentation, please. 
In docs you write
 **wheelPropagation Default: false**  

![image](https://user-images.githubusercontent.com/6988442/82753221-abd56680-9dcc-11ea-98fc-a13fba93481e.png)

https://binaryify.github.io/vue-custom-scrollbar/en/#wheelpropagation-boolean

https://github.com/Binaryify/vue-custom-scrollbar/blob/54d9da984b552730feba89d8161840c34718a8ef/dist/vueScrollbar.common.js#L1750

**Comment by Binaryify** [comment]
oh, I didn't realize it, will update the documentation , thank for the feedback~

**Comment by Binaryify** [comment]
just fixed that documentation , you can check it now

**Comment by Binaryify** [comment]
just fixed that documentation , you can check it now

**Comment by veremey** [comment]
Thanks!
