### ISSUE TITLE
Click is not registered for iOS on first interaction

### ISSUE THREAD

**Issue by ryanblak** [Binaryify/vue-custom-scrollbar#5]
When interacting with elements passed into the scrollbar slot, the first touch does not register as a click on iOS Safari.

In `vue-scrollbar.vue` there is the event handling code `@mouseover.once="update"`. The update method calls a `ps.update`, which results in the content changing. In iOS, this results in the events lower in the hierarchy not firing; one of those events is `click`. This [StackOverflow post](https://stackoverflow.com/a/22444819) explains the issue well.

**Comment by Binaryify** [comment]
thank for the feedback~
