### ISSUE TITLE
Update perfect-scrollbar to ^1.5.1 to fix "Cannot read property 'scrollTop' of null" issue

### ISSUE THREAD

**Issue by MarkParnwell** [Binaryify/vue-custom-scrollbar#68]
We're encountering a lot of `Cannot read property 'scrollTop' of null` errors (https://github.com/mdbootstrap/perfect-scrollbar/issues/835). 

This was fixed in perfect-scrollbar 1.5.1 (https://github.com/mdbootstrap/perfect-scrollbar/releases/tag/1.5.1), but looking at the /dist/ of 1.4.1 published on NPM, version 1.5.0 is still bundled (like here https://github.com/Binaryify/vue-custom-scrollbar/blob/master/dist/vueScrollbar.umd.min.js#L3).

Could we bump the perfect-scrollbar version, rebuild and publish?

Thank you

**Comment by Binaryify** [comment]
sure

**Comment by Binaryify** [comment]
please check v1.4.2~

**Comment by MarkParnwell** [comment]
Unfortunately, it seems the distributables are still out of date on NPM and here... https://github.com/Binaryify/vue-custom-scrollbar/blob/master/dist/vueScrollbar.umd.min.js#L3
I think it needs a rebuild

**Comment by Binaryify** [comment]
wait

**Comment by Binaryify** [comment]
plz check v1.4.3

**Comment by MarkParnwell** [comment]
Excellent! Seems to be updated now. Now showing v1.5.3. Thank you 🙌
